kops create cluster \
--name=kops.samdevopsinuse.ml \
--state=s3://kops.samdevopsinuse.ml \
--authorization RBAC \
--zones=eu-west-1b \
--node-count=2 \
--master-count=1 \
--node-size=t2.micro \
--master-size=t2.micro \
--dns-zone=kops.samdevopsinuse.ml \
--out=samdevopsinuse_terraform \
--target=terraform \
--ssh-public-key=~/.ssh/samdevopsinuse.pub